// Canonical pathway definitions for the Learning Center.
// Class titles are matched against LearningClass.title (case-insensitive).

export const LEARNING_PATHWAYS = [
  {
    id: 'job_ready',
    label: 'Job Ready Path',
    description: 'Build the core skills needed to find, get, and keep a job — from writing a resume to showing up ready every day.',
    icon: '💼',
    color: 'bg-blue-50 border-blue-200',
    iconBg: 'bg-blue-100',
    iconText: 'text-blue-700',
    progressColor: 'bg-blue-500',
    certificate_category: 'job_ready',
    classTitles: [
      'How This Program Works',
      'Resume Basics',
      'Interview Basics',
      'Workplace Communication',
      'How to Keep a Job',
    ],
  },
  {
    id: 'stability',
    label: 'Stability Path',
    description: 'Learn what you need to stay housed, get around, manage money, and handle the stress of daily life.',
    icon: '🏠',
    color: 'bg-green-50 border-green-200',
    iconBg: 'bg-green-100',
    iconText: 'text-green-700',
    progressColor: 'bg-green-500',
    certificate_category: 'stability',
    classTitles: [
      'Why ID and Documents Matter',
      'What You Need to Rent a Place',
      'Transportation Planning',
      'Budgeting Basics',
      'Managing Stress and Triggers',
    ],
  },
  {
    id: 'digital_readiness',
    label: 'Digital Basics Path',
    description: 'Get comfortable with computers, email, and the internet so you can apply for jobs and manage documents online.',
    icon: '💻',
    color: 'bg-cyan-50 border-cyan-200',
    iconBg: 'bg-cyan-100',
    iconText: 'text-cyan-700',
    progressColor: 'bg-cyan-500',
    certificate_category: 'digital_readiness',
    classTitles: [
      'Basic Computer Skills',
      'How to Create and Use an Email Address',
      'How to Send an Email',
      'How to Upload Documents',
      'How to Search for Jobs Online',
    ],
  },
  {
    id: 'financial_basics',
    label: 'Financial Basics Path',
    description: 'Understand how money, credit, and budgeting work so your first paycheck can start building a better future.',
    icon: '💰',
    color: 'bg-yellow-50 border-yellow-200',
    iconBg: 'bg-yellow-100',
    iconText: 'text-yellow-700',
    progressColor: 'bg-yellow-500',
    certificate_category: 'financial_basics',
    classTitles: [
      'How Money Works',
      'Budgeting Basics',
      'How Credit Works',
      'How to Build Credit Safely',
      'First Paycheck Planning',
    ],
  },
  {
    id: 'life_skills',
    label: 'Life Skills Path',
    description: 'Practical everyday skills — managing your time, communicating clearly, resolving conflict, cooking, and keeping a clean space.',
    icon: '🌱',
    color: 'bg-rose-50 border-rose-200',
    iconBg: 'bg-rose-100',
    iconText: 'text-rose-700',
    progressColor: 'bg-rose-500',
    certificate_category: 'life_skills',
    classTitles: [
      'Time Management Basics',
      'Communication Skills',
      'Conflict Resolution',
      'Cooking for Beginners',
      'Basic Household Cleaning',
    ],
  },
];