import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const TRAINING_MODULES = [
  {
    training_id: 'cm_intake_001',
    role: 'case_manager',
    module_title: 'How to Complete a Client Intake',
    module_description: 'Learn how to gather essential client information and complete intake assessments.',
    estimated_minutes: 12,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Access the Intake Module',
        description: 'Navigate to the Intake section to begin a new client assessment.',
        action_type: 'click',
        target_element: '[href="/intake"]',
        content: 'Click on the Intake link in the navigation menu.',
      },
      {
        step_number: 2,
        title: 'Select a Resident',
        description: 'Choose the resident you want to complete an intake for.',
        action_type: 'read',
        content: 'You can search by name or ID in the resident selection dropdown.',
      },
      {
        step_number: 3,
        title: 'Personal Information',
        description: 'Fill in basic demographic information.',
        action_type: 'fill',
        target_element: '[name="first_name"]',
        content: 'Complete the personal details section with accurate information.',
      },
      {
        step_number: 4,
        title: 'Housing Assessment',
        description: 'Document the resident\'s current housing situation.',
        action_type: 'read',
        content: 'Select their current housing status: stable, transitional, shelter, unstable, or none.',
      },
      {
        step_number: 5,
        title: 'Employment History',
        description: 'Record their work experience and job preferences.',
        action_type: 'read',
        content: 'Document years of experience, previous industries, and job interests.',
      },
      {
        step_number: 6,
        title: 'Barriers Assessment',
        description: 'Identify any barriers to employment or housing.',
        action_type: 'read',
        content: 'Check all applicable barriers such as legal issues, education gaps, or transportation challenges.',
      },
      {
        step_number: 7,
        title: 'Document Review',
        description: 'Verify all documents are collected and uploaded.',
        action_type: 'read',
        content: 'Ensure required documents like ID, SSN card, and work authorization are present.',
      },
      {
        step_number: 8,
        title: 'Submit Intake',
        description: 'Complete the assessment and submit for processing.',
        action_type: 'click',
        target_element: 'button:contains("Submit")',
        content: 'Review all information one final time before submitting.',
      },
    ],
  },
  {
    training_id: 'cm_caseload_002',
    role: 'case_manager',
    module_title: 'Managing Your Caseload',
    module_description: 'Master the tools for viewing, filtering, and managing your resident caseload.',
    estimated_minutes: 10,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'View Your Residents',
        description: 'Access the Residents page to see your assigned clients.',
        action_type: 'click',
        target_element: '[href="/residents"]',
        content: 'The Residents page shows all clients in your caseload.',
      },
      {
        step_number: 2,
        title: 'Search and Filter',
        description: 'Use search and filter tools to find specific residents.',
        action_type: 'read',
        content: 'Search by name, ID, or filter by status (active, housing eligible, employed, etc.).',
      },
      {
        step_number: 3,
        title: 'View Resident Status',
        description: 'Check the current status and progress of each resident.',
        action_type: 'read',
        content: 'Color-coded badges show housing status, employment status, and completion milestones.',
      },
      {
        step_number: 4,
        title: 'Open Resident Profile',
        description: 'Click on a resident to view their detailed profile.',
        action_type: 'click',
        target_element: '.resident-card',
        content: 'The profile shows intake data, housing placement, case notes, and progress.',
      },
      {
        step_number: 5,
        title: 'Update Resident Information',
        description: 'Modify resident data and add case notes.',
        action_type: 'read',
        content: 'You can update status, notes, assignment information, and barriers from the profile.',
      },
      {
        step_number: 6,
        title: 'Track Assignments',
        description: 'Monitor housing and service assignments for your clients.',
        action_type: 'read',
        content: 'View current housing placements, pending referrals, and transportation arrangements.',
      },
    ],
  },
  {
    training_id: 'cm_housing_003',
    role: 'case_manager',
    module_title: 'Housing Referral Workflow',
    module_description: 'Learn how to submit housing referrals and track placement outcomes.',
    estimated_minutes: 14,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Access Housing Referrals',
        description: 'Navigate to the Housing Referrals section.',
        action_type: 'click',
        target_element: '[href="/housing-referrals"]',
        content: 'The Housing Referrals page manages the referral pipeline.',
      },
      {
        step_number: 2,
        title: 'Create New Referral',
        description: 'Start a new housing referral for a resident.',
        action_type: 'click',
        target_element: 'button:contains("New Referral")',
        content: 'Select the resident and housing program type.',
      },
      {
        step_number: 3,
        title: 'Resident Information',
        description: 'Provide resident details for the housing provider.',
        action_type: 'read',
        content: 'Share contact info, employment status, and housing needs summary.',
      },
      {
        step_number: 4,
        title: 'Barriers and Accommodations',
        description: 'Document any barriers relevant to housing placement.',
        action_type: 'read',
        content: 'List barriers that may affect placement and any needed accommodations.',
      },
      {
        step_number: 5,
        title: 'Upload Documents',
        description: 'Attach supporting documents for the referral.',
        action_type: 'read',
        content: 'Attach ID, income verification, background check, and other required docs.',
      },
      {
        step_number: 6,
        title: 'Select Housing Provider',
        description: 'Choose the target housing organization.',
        action_type: 'click',
        target_element: '[name="provider"]',
        content: 'Select from approved housing providers.',
      },
      {
        step_number: 7,
        title: 'Submit Referral',
        description: 'Complete and submit the referral package.',
        action_type: 'click',
        target_element: 'button:contains("Submit")',
        content: 'Review all information before final submission.',
      },
    ],
  },
  {
    training_id: 'cm_transport_004',
    role: 'case_manager',
    module_title: 'Transportation Requests',
    module_description: 'Manage transportation needs for your clients.',
    estimated_minutes: 8,
    completion_required: false,
    steps: [
      {
        step_number: 1,
        title: 'Access Transportation Hub',
        description: 'Navigate to the transportation management section.',
        action_type: 'click',
        target_element: '[href="/transportation"]',
        content: 'View and manage all transportation requests.',
      },
      {
        step_number: 2,
        title: 'Request a Ride',
        description: 'Submit a new transportation request.',
        action_type: 'click',
        target_element: 'button:contains("New Request")',
        content: 'Specify pickup location, destination, date, and reason.',
      },
      {
        step_number: 3,
        title: 'Select Request Type',
        description: 'Choose the purpose of transportation.',
        action_type: 'read',
        content: 'Options: employment, medical, court, housing search, document retrieval, program, other.',
      },
      {
        step_number: 4,
        title: 'Schedule Transportation',
        description: 'Set the date and time for pickup.',
        action_type: 'read',
        content: 'Requests must be made at least 48 hours in advance.',
      },
      {
        step_number: 5,
        title: 'Track Request Status',
        description: 'Monitor the transportation request progress.',
        action_type: 'read',
        content: 'View driver assignment, estimated time, and completion status.',
      },
    ],
  },
  {
    training_id: 'hs_beds_001',
    role: 'housing_staff',
    module_title: 'Managing Bed Inventory',
    module_description: 'Learn to manage house beds, occupancy, and availability.',
    estimated_minutes: 11,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Access Housing Operations',
        description: 'Navigate to the housing operations dashboard.',
        action_type: 'click',
        target_element: '[href="/housing"]',
        content: 'View all managed houses and bed inventory.',
      },
      {
        step_number: 2,
        title: 'View House Details',
        description: 'Select a house to view bed status.',
        action_type: 'read',
        content: 'See occupancy rates, available beds, and bed assignments.',
      },
      {
        step_number: 3,
        title: 'Update Bed Status',
        description: 'Mark beds as available, occupied, or maintenance.',
        action_type: 'click',
        target_element: '.bed-status-toggle',
        content: 'Click on a bed to update its status.',
      },
      {
        step_number: 4,
        title: 'Assign Residents',
        description: 'Place residents in available beds.',
        action_type: 'read',
        content: 'Verify resident eligibility and move-in requirements before assignment.',
      },
      {
        step_number: 5,
        title: 'Track Occupancy',
        description: 'Monitor house occupancy rates and capacity.',
        action_type: 'read',
        content: 'Dashboard shows real-time occupancy percentages and income generation.',
      },
      {
        step_number: 6,
        title: 'Schedule Maintenance',
        description: 'Mark beds for cleaning or maintenance.',
        action_type: 'read',
        content: 'Set maintenance schedules to keep houses in compliance.',
      },
    ],
  },
  {
    training_id: 'hs_referral_002',
    role: 'housing_staff',
    module_title: 'Processing Referrals and Placements',
    module_description: 'Handle incoming housing referrals and complete placements.',
    estimated_minutes: 13,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Review Incoming Referrals',
        description: 'Check the referral queue for new applications.',
        action_type: 'read',
        content: 'View pending referrals with resident information and requirements.',
      },
      {
        step_number: 2,
        title: 'Assess Compatibility',
        description: 'Review resident barriers and house requirements.',
        action_type: 'read',
        content: 'Ensure resident needs align with house program and capacity.',
      },
      {
        step_number: 3,
        title: 'Approve or Decline',
        description: 'Make an approval decision on the referral.',
        action_type: 'click',
        target_element: '.approval-button',
        content: 'Add notes explaining your decision.',
      },
      {
        step_number: 4,
        title: 'Assign a Bed',
        description: 'Select and reserve a bed for the approved resident.',
        action_type: 'read',
        content: 'Choose an available bed matching resident needs.',
      },
      {
        step_number: 5,
        title: 'Set Move-In Date',
        description: 'Schedule the resident\'s move-in date.',
        action_type: 'read',
        content: 'Coordinate with the resident and referring organization.',
      },
      {
        step_number: 6,
        title: 'Generate Placement Confirmation',
        description: 'Create confirmation documentation.',
        action_type: 'read',
        content: 'Documents include house rules, fee information, and contact details.',
      },
      {
        step_number: 7,
        title: 'Track Placement Status',
        description: 'Monitor the placement lifecycle.',
        action_type: 'read',
        content: 'View move-in confirmation, current status, and exit planning.',
      },
    ],
  },
  {
    training_id: 'es_matching_001',
    role: 'employment_staff',
    module_title: 'Job Matching Workflow',
    module_description: 'Use the matching engine to connect residents with job opportunities.',
    estimated_minutes: 10,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Access Job Matching',
        description: 'Navigate to the job matching dashboard.',
        action_type: 'click',
        target_element: '[href="/job-matching"]',
        content: 'View job listings and resident matches.',
      },
      {
        step_number: 2,
        title: 'Review Job Listings',
        description: 'See available job opportunities from employers.',
        action_type: 'read',
        content: 'View job titles, requirements, pay rates, and employer info.',
      },
      {
        step_number: 3,
        title: 'Generate Matches',
        description: 'Run the matching engine to identify qualified residents.',
        action_type: 'click',
        target_element: 'button:contains("Generate Matches")',
        content: 'The system scores residents against job requirements.',
      },
      {
        step_number: 4,
        title: 'Review Match Scores',
        description: 'Examine the quality of recommended matches.',
        action_type: 'read',
        content: 'Match scores show fit percentage and identified strengths/gaps.',
      },
      {
        step_number: 5,
        title: 'Present to Resident',
        description: 'Share job recommendations with the resident.',
        action_type: 'read',
        content: 'Discuss opportunities and help resident decide whether to apply.',
      },
      {
        step_number: 6,
        title: 'Track Application Status',
        description: 'Monitor the application and interview process.',
        action_type: 'read',
        content: 'Update status as resident progresses through hiring pipeline.',
      },
    ],
  },
  {
    training_id: 'po_caseload_001',
    role: 'probation_officer',
    module_title: 'Monitoring Your Caseload',
    module_description: 'Oversee residents on probation and track compliance.',
    estimated_minutes: 9,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'View Assigned Residents',
        description: 'See all residents under your probation supervision.',
        action_type: 'click',
        target_element: '[href="/residents"]',
        content: 'Dashboard shows supervised residents and their current status.',
      },
      {
        step_number: 2,
        title: 'Check Compliance Status',
        description: 'Review probation compliance for each resident.',
        action_type: 'read',
        content: 'See check-in history, program participation, and violations.',
      },
      {
        step_number: 3,
        title: 'Add Probation Notes',
        description: 'Document observations and interactions.',
        action_type: 'read',
        content: 'Add case notes about resident progress and any concerns.',
      },
      {
        step_number: 4,
        title: 'Schedule Check-Ins',
        description: 'Manage probation check-in appointments.',
        action_type: 'read',
        content: 'Set up required regular meetings and document attendance.',
      },
      {
        step_number: 5,
        title: 'Flag Violations',
        description: 'Report any probation violations or concerning behavior.',
        action_type: 'read',
        content: 'Create incident reports and notify administrators.',
      },
    ],
  },
  {
    training_id: 'emp_portal_001',
    role: 'employer',
    module_title: 'Using the Employer Portal',
    module_description: 'Manage your job postings and candidate pipeline.',
    estimated_minutes: 7,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Access Your Portal',
        description: 'Log in to the employer dashboard.',
        action_type: 'click',
        target_element: '[href="/employer-portal"]',
        content: 'View your company profile and active jobs.',
      },
      {
        step_number: 2,
        title: 'Post a Job',
        description: 'Create a new job listing.',
        action_type: 'click',
        target_element: 'button:contains("Post Job")',
        content: 'Fill in job details, requirements, and compensation.',
      },
      {
        step_number: 3,
        title: 'Review Candidates',
        description: 'View qualified resident candidates.',
        action_type: 'read',
        content: 'See resumes, background info, and match scores.',
      },
      {
        step_number: 4,
        title: 'Manage Hiring Pipeline',
        description: 'Track candidates through interview and hiring stages.',
        action_type: 'read',
        content: 'Update status as candidates progress through your process.',
      },
    ],
  },
  {
    training_id: 'res_start_001',
    role: 'resident',
    module_title: 'Getting Started with Your Account',
    module_description: 'Learn the basics of using your resident dashboard.',
    estimated_minutes: 8,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Welcome to Pathways',
        description: 'Overview of your resident account and available tools.',
        action_type: 'read',
        content: 'Your dashboard provides access to tasks, appointments, job opportunities, and support resources.',
      },
      {
        step_number: 2,
        title: 'View Your Tasks',
        description: 'Check your assigned tasks and action items.',
        action_type: 'click',
        target_element: '[href="/my-tasks"]',
        content: 'Tasks show action items your case manager needs you to complete.',
      },
      {
        step_number: 3,
        title: 'Manage Your Appointments',
        description: 'View and update your scheduled appointments.',
        action_type: 'click',
        target_element: '[href="/my-appointments"]',
        content: 'See meetings with your case manager, interviews, and program sessions.',
      },
      {
        step_number: 4,
        title: 'Explore Job Opportunities',
        description: 'Browse and apply for recommended job matches.',
        action_type: 'click',
        target_element: '[href="/my-jobs"]',
        content: 'View jobs matched to your skills and interests.',
      },
      {
        step_number: 5,
        title: 'Access Support Resources',
        description: 'Find learning modules and support services.',
        action_type: 'click',
        target_element: '[href="/my-supports"]',
        content: 'View available training, classes, and support programs.',
      },
    ],
  },
  {
    training_id: 'admin_overview_001',
    role: 'admin',
    module_title: 'System Administration Overview',
    module_description: 'Master the admin control center and core functions.',
    estimated_minutes: 15,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Admin Control Center',
        description: 'Navigate the central admin dashboard.',
        action_type: 'click',
        target_element: '[href="/admin/control-center"]',
        content: 'The control center provides access to all admin functions.',
      },
      {
        step_number: 2,
        title: 'System Overview Tab',
        description: 'Monitor key system metrics and resident statistics.',
        action_type: 'read',
        content: 'See dashboard with active residents, housing, staff, and pending requests.',
      },
      {
        step_number: 3,
        title: 'Manage Users',
        description: 'Add and manage staff members and their roles.',
        action_type: 'read',
        content: 'Control who can access the system and what they can do.',
      },
      {
        step_number: 4,
        title: 'Monitor Queues',
        description: 'Check pending requests and approvals.',
        action_type: 'read',
        content: 'View onboarding requests, housing approvals, and other queued items.',
      },
      {
        step_number: 5,
        title: 'Review Audit Logs',
        description: 'Check system activity and user actions.',
        action_type: 'click',
        target_element: '[href="/admin/audit"]',
        content: 'Audit logs track important system changes for compliance.',
      },
      {
        step_number: 6,
        title: 'Configure Settings',
        description: 'Customize system settings and parameters.',
        action_type: 'read',
        content: 'Manage organization info, program settings, and user preferences.',
      },
      {
        step_number: 7,
        title: 'Run Diagnostics',
        description: 'Check system health and identify issues.',
        action_type: 'read',
        content: 'Run diagnostic checks to ensure smooth operation.',
      },
      {
        step_number: 8,
        title: 'Generate Reports',
        description: 'Create reports on outcomes and system usage.',
        action_type: 'read',
        content: 'Reports help track program effectiveness and metrics.',
      },
    ],
  },
  {
    training_id: 'super_admin_complete_001',
    role: 'super_admin',
    module_title: 'Complete System Control',
    module_description: 'Full system administration including advanced features.',
    estimated_minutes: 20,
    completion_required: true,
    steps: [
      {
        step_number: 1,
        title: 'Super Admin Dashboard',
        description: 'Access the highest level system control.',
        action_type: 'click',
        target_element: '[href="/admin/control-center"]',
        content: 'Super admin has full visibility and control over all system functions.',
      },
      {
        step_number: 2,
        title: 'Team Management',
        description: 'Add, remove, and manage all staff members.',
        action_type: 'read',
        content: 'Control staff access, roles, permissions, and responsibilities.',
      },
      {
        step_number: 3,
        title: 'Role Assignment',
        description: 'Assign and modify staff roles and capabilities.',
        action_type: 'read',
        content: 'Set what each role can do with granular permission controls.',
      },
      {
        step_number: 4,
        title: 'Training Management',
        description: 'Configure mandatory training for new staff.',
        action_type: 'read',
        content: 'Enable training requirements by role and track completion.',
      },
      {
        step_number: 5,
        title: 'System Health Monitoring',
        description: 'Check system performance and resolve issues.',
        action_type: 'read',
        content: 'Monitor system metrics, identify bottlenecks, and optimize performance.',
      },
      {
        step_number: 6,
        title: 'Organization Management',
        description: 'Manage organization settings and hierarchy.',
        action_type: 'read',
        content: 'Configure organization structure, sites, and operational parameters.',
      },
      {
        step_number: 7,
        title: 'Advanced Audit & Compliance',
        description: 'Access detailed audit logs and compliance reports.',
        action_type: 'read',
        content: 'Monitor all system activities for security and compliance.',
      },
      {
        step_number: 8,
        title: 'Data Management',
        description: 'Manage data backups, exports, and integrations.',
        action_type: 'read',
        content: 'Control how data is stored, backed up, and shared.',
      },
      {
        step_number: 9,
        title: 'Override Capabilities',
        description: 'Override restrictions and manage exceptions.',
        action_type: 'read',
        content: 'Super admin can override any system restriction when needed.',
      },
      {
        step_number: 10,
        title: 'System Configuration',
        description: 'Configure advanced system settings and integrations.',
        action_type: 'read',
        content: 'Set up API integrations, webhooks, and advanced features.',
      },
    ],
  },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin' && user?.role !== 'super_admin') {
      return Response.json({ error: 'Unauthorized' }, { status: 403 });
    }

    const results = [];
    for (const module of TRAINING_MODULES) {
      const created = await base44.asServiceRole.entities.Training.create({
        ...module,
        created_date: new Date().toISOString().split('T')[0],
        updated_date: new Date().toISOString().split('T')[0],
      });
      results.push(created);
    }

    return Response.json({
      success: true,
      created: results.length,
      message: `${results.length} training modules created`,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});