import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const TRACKS = [
  { track_id: 'track_01', title: 'Reentry Foundations', description: 'Essential skills and knowledge for successful reentry after incarceration', icon: '🔓', color: '#F59E0B', order: 1, target_populations: ['reentry'], is_baseline: false },
  { track_id: 'track_02', title: 'Housing Stability', description: 'Learn how to find, secure, and maintain stable housing', icon: '🏠', color: '#10B981', order: 2, target_populations: ['reentry','homeless','at_risk'], is_baseline: false },
  { track_id: 'track_03', title: 'Employment & Career Readiness', description: 'Everything you need to get and keep a good job', icon: '💼', color: '#3B82F6', order: 3, target_populations: ['all'], is_baseline: false },
  { track_id: 'track_04', title: 'Financial Stability & Credit', description: 'Build financial literacy, banking skills, and credit', icon: '💰', color: '#8B5CF6', order: 4, target_populations: ['all'], is_baseline: true },
  { track_id: 'track_05', title: 'Credit Counseling & How Money Really Works', description: 'Deep-dive into credit, debt, and wealth-building strategies', icon: '📊', color: '#EC4899', order: 5, target_populations: ['all'], is_baseline: true },
  { track_id: 'track_06', title: 'Technology & Digital Literacy', description: 'Essential tech skills for modern independent living', icon: '💻', color: '#06B6D4', order: 6, target_populations: ['all'], is_baseline: true },
  { track_id: 'track_07', title: 'Recovery, Wellness & Stability', description: 'Tools for maintaining recovery and mental wellness', icon: '🌱', color: '#34D399', order: 7, target_populations: ['recovery','reentry'], is_baseline: false },
  { track_id: 'track_08', title: 'Life Management & Independent Living', description: 'Practical daily life skills for independence', icon: '🏡', color: '#F97316', order: 8, target_populations: ['all'], is_baseline: false },
  { track_id: 'track_09', title: 'Benefits, IDs & System Navigation', description: 'How to access IDs, benefits, and navigate government systems', icon: '🪪', color: '#EAB308', order: 9, target_populations: ['reentry','homeless'], is_baseline: false },
  { track_id: 'track_10', title: 'Veteran Life Skills', description: 'Specialized resources and skills for veterans transitioning to civilian life', icon: '🎖️', color: '#64748B', order: 10, target_populations: ['veteran'], is_baseline: false },
  { track_id: 'track_11', title: 'Legal Navigation', description: 'Understanding legal rights, records, and the justice system', icon: '⚖️', color: '#DC2626', order: 11, target_populations: ['reentry'], is_baseline: false },
  { track_id: 'track_12', title: 'Entrepreneurship & Side Income', description: 'Start a business or earn income on your own terms', icon: '🚀', color: '#7C3AED', order: 12, target_populations: ['all'], is_baseline: false },
];

const CLASSES = [
  // Track 1 - Reentry Foundations
  { track_id: 'track_01', order: 1, title: 'Orientation to Pathways and Your Program', description: 'Welcome to the program. Learn what resources are available to you and how to navigate your journey successfully.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['reentry'], completion_required: true, prerequisites: [] },
  { track_id: 'track_01', order: 2, title: 'Reentry Success Planning', description: 'Build a personal reentry plan with realistic goals, timelines, and support systems.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['reentry'], completion_required: true, prerequisites: [] },
  { track_id: 'track_01', order: 3, title: 'How to Navigate Probation and Parole Requirements', description: 'Understand your supervision conditions, reporting requirements, and how to stay compliant.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['reentry'], completion_required: true, prerequisites: [] },
  { track_id: 'track_01', order: 4, title: 'Rebuilding Your Life After Incarceration', description: 'Practical strategies for rebuilding relationships, identity, and purpose after release.', estimated_minutes: 50, difficulty: 'beginner', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_01', order: 5, title: 'Recovery-Focused Daily Structure', description: 'Build healthy routines that support both your recovery and your reentry goals.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['reentry','recovery'], completion_required: false, prerequisites: [] },
  { track_id: 'track_01', order: 6, title: 'Veteran Reintegration Basics', description: 'Special considerations and resources for veterans navigating reentry.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['veteran','reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_01', order: 7, title: 'Community Resources 101', description: 'Map out the resources in your community including food banks, shelters, legal aid, and more.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_01', order: 8, title: 'Understanding Case Management', description: 'Learn how case management works and how to get the most out of your case manager relationship.', estimated_minutes: 25, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_01', order: 9, title: 'Personal Responsibility and Accountability', description: 'Develop the mindset and habits of personal responsibility that lead to long-term success.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_01', order: 10, title: 'Goal Setting and Weekly Action Planning', description: 'Learn SMART goal-setting and how to break big goals into weekly actionable steps.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },

  // Track 2 - Housing Stability
  { track_id: 'track_02', order: 1, title: 'Housing Readiness 101', description: 'Understand what landlords look for and how to prepare yourself for the housing search.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['reentry','homeless','at_risk'], completion_required: true, prerequisites: [] },
  { track_id: 'track_02', order: 2, title: 'How to Search for Housing', description: 'Step-by-step guide to finding affordable housing using online tools, local resources, and networks.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_02', order: 3, title: 'How to Fill Out a Rental Application', description: 'Walk through a real rental application and learn what each section means and how to answer correctly.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_02', order: 4, title: 'Understanding Leases and House Rules', description: 'Learn to read and understand a lease agreement so you know your rights and obligations.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_02', order: 5, title: 'Tenant Rights and Responsibilities', description: 'Know your legal rights as a tenant and what responsibilities you have under the law.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_02', order: 6, title: 'How Security Deposits Work', description: 'Understand security deposit rules, when you get it back, and how to protect yourself.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_02', order: 7, title: 'Utility Setup Basics', description: 'How to set up electricity, gas, water, and internet when you move into a new place.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_02', order: 8, title: 'Shared Living and Roommate Skills', description: 'Navigate shared housing successfully with communication, boundaries, and conflict resolution.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_02', order: 9, title: 'Communicating with Landlords', description: 'Professional communication strategies for dealing with landlords and property managers.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_02', order: 10, title: 'Avoiding Evictions', description: 'Learn the most common reasons for eviction and proven strategies to prevent them.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_02', order: 11, title: 'Understanding Tenant Screening Reports', description: 'Learn what landlords see when they run your background and credit check.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_02', order: 12, title: 'Fixing Housing Barriers on Your Record', description: 'Strategies for addressing criminal records, eviction history, and bad credit in your housing search.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_02', order: 13, title: 'Transitional Housing to Independent Living', description: 'Plan and execute a successful transition from transitional housing to your own place.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['reentry','homeless'], completion_required: false, prerequisites: [] },
  { track_id: 'track_02', order: 14, title: 'Keeping a Home Clean, Safe, and Stable', description: 'Essential home maintenance, cleaning routines, and safety practices for keeping your housing long-term.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },

  // Track 3 - Employment
  { track_id: 'track_03', order: 1, title: 'Employment Readiness Bootcamp', description: 'A comprehensive overview of everything you need to be employment-ready.', estimated_minutes: 60, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_03', order: 2, title: 'Soft Skills for the Workplace', description: 'Communication, teamwork, reliability, and other non-technical skills employers value most.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_03', order: 3, title: 'How to Explain Your Background in an Interview', description: 'Craft honest, confident, and strategic answers about your criminal history for employers.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 4, title: 'Resume Building', description: 'Build a professional resume from scratch, even with gaps in your work history.', estimated_minutes: 60, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_03', order: 5, title: 'Job Applications Step by Step', description: 'Learn how to complete job applications accurately and professionally, online and in person.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_03', order: 6, title: 'Interview Skills', description: 'Prepare for interviews with practice questions, body language tips, and follow-up strategies.', estimated_minutes: 60, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_03', order: 7, title: 'Workplace Communication', description: 'How to communicate professionally with supervisors, coworkers, and customers.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 8, title: 'Time Management and Showing Up', description: 'Reliability strategies, time management tools, and how to never be late to work.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 9, title: 'Conflict Resolution at Work', description: 'Navigate workplace conflicts professionally without jeopardizing your job.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 10, title: 'Professionalism and Work Ethics', description: 'Understand workplace expectations, dress codes, and professional conduct standards.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 11, title: 'Job Retention Skills', description: 'Proven strategies to keep your job, advance, and avoid common mistakes that get people fired.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_03', order: 12, title: 'Career Pathways Exploration', description: 'Explore career options that match your skills, interests, and life situation.', estimated_minutes: 50, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 13, title: 'Apprenticeships and Skilled Trades', description: 'Learn about paid apprenticeship programs and in-demand trade careers.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 14, title: 'Understanding Background Checks', description: 'Know what employers see in your background check and how to prepare your response.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 15, title: 'Second-Chance Employment', description: 'Identify employers who actively hire people with records and how to approach them.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 16, title: 'Transportation Planning for Work', description: 'Plan reliable transportation routes so you can get to work on time every day.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 17, title: 'Work Uniforms, Tools, and Readiness', description: 'Prepare the physical items you need for work including clothes, tools, and ID.', estimated_minutes: 25, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_03', order: 18, title: 'How to Keep a Job for 90 Days', description: 'The first 90 days are critical. Learn the specific strategies that lead to long-term employment.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_03', order: 19, title: 'Building Toward Promotion and Leadership', description: 'Once employed, learn how to position yourself for advancement and leadership roles.', estimated_minutes: 50, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },

  // Track 4 - Financial Stability
  { track_id: 'track_04', order: 1, title: 'Financial Foundations', description: 'The basics of personal finance: income, expenses, and the mindset for financial health.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_04', order: 2, title: 'Budgeting Basics', description: 'Create a simple monthly budget that actually works for your income and needs.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_04', order: 3, title: 'Banking 101', description: 'Understand how banks work and why having a bank account is essential.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_04', order: 4, title: 'Opening a Checking and Savings Account', description: 'Step-by-step guide to opening your first bank account, even with a troubled banking history.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_04', order: 5, title: 'Direct Deposit and Paychecks', description: 'Set up direct deposit and understand how your paycheck works.', estimated_minutes: 25, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 6, title: 'Understanding Taxes and W-2s', description: 'Understand tax basics, W-2 forms, and how to file your taxes for free.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 7, title: 'Debt Basics', description: 'Understand different types of debt and your options for managing them.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 8, title: 'How Credit Works', description: 'Introduction to credit: what it is, why it matters, and how it affects your life.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_04', order: 9, title: 'Credit Reports and Credit Scores', description: 'Understand the difference between credit reports and credit scores and how both are calculated.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_04', order: 10, title: 'How to Read a Credit Report', description: 'Walk through a real credit report line by line to understand what each section means.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 11, title: 'Disputing Errors on Your Credit Report', description: 'Learn the legal process for disputing inaccurate items on your credit report.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 12, title: 'Rebuilding Credit Step by Step', description: 'A practical timeline and strategy for rebuilding damaged credit from the ground up.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_04', order: 13, title: 'Credit Cards: Smart Use vs Bad Use', description: 'How to use credit cards as tools without falling into the trap of revolving debt.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 14, title: 'Avoiding Predatory Loans', description: 'Identify and avoid payday loans, title loans, and other predatory financial products.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_04', order: 15, title: 'Identity Theft and Fraud Protection', description: 'Protect your financial identity and know what to do if you are a victim of fraud.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 16, title: 'Emergency Savings', description: 'Build an emergency fund even on a tight budget to protect against financial crises.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 17, title: 'Financial Wellness for Families', description: 'Manage household finances as a family unit with shared goals and responsibilities.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 18, title: 'Planning for a Car Purchase', description: 'Navigate the car-buying process including financing, insurance, and total cost of ownership.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 19, title: 'Planning for Housing Costs', description: 'Budget for rent, utilities, deposits, and moving costs so housing does not break your budget.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 20, title: 'Benefits, Income, and Work Incentives', description: 'Understand how working affects your benefits and how to manage the transition from benefits to income.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_04', order: 21, title: 'Financial Goal Setting', description: 'Set and track short-term and long-term financial goals with real milestones.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },

  // Track 5 - Credit Counseling
  { track_id: 'track_05', order: 1, title: 'How the US Financial System Works', description: 'Understand banks, credit unions, the Federal Reserve, and how money flows through the economy.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_05', order: 2, title: 'The Federal Reserve and How Interest Rates Affect You', description: 'How the Fed sets interest rates and how those rates impact your loans, credit cards, and savings.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 3, title: 'How Banks Make Money and What That Means for You', description: 'Understand bank business models so you can use banking services more strategically.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 4, title: 'Understanding Inflation and Your Buying Power', description: 'How inflation erodes purchasing power and strategies to protect your money.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 5, title: 'How Wealth Is Built Over Time', description: 'The principles of compound interest, asset accumulation, and long-term wealth building.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 6, title: 'The Psychology of Money and Spending Habits', description: 'Understand the emotional and psychological drivers behind financial decisions.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 7, title: 'Needs vs Wants vs Investments', description: 'Classify your spending to prioritize necessities, reduce wants, and grow investments.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_05', order: 8, title: 'How to Work with a Credit Counselor', description: 'What credit counselors do, how to find a legitimate one, and what to expect from sessions.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 9, title: 'Debt Management Plans Explained', description: 'Understand formal debt management plans and when they make sense for your situation.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 10, title: 'Negotiating with Creditors', description: 'Scripts and strategies for negotiating directly with creditors to reduce debt.', estimated_minutes: 50, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 11, title: 'Collections: What to Do When You Are in Collections', description: 'Know your rights under the FDCPA and how to handle collection accounts strategically.', estimated_minutes: 50, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 12, title: 'Charge-Offs and How to Handle Them', description: 'What a charge-off means, how long it stays on your report, and what to do about it.', estimated_minutes: 45, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 13, title: 'Secured vs Unsecured Debt', description: 'Understand the difference between secured and unsecured debt and how each affects your finances.', estimated_minutes: 35, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 14, title: 'Student Loans and Income-Based Repayment', description: 'Navigate federal student loan programs, forgiveness options, and income-driven repayment plans.', estimated_minutes: 50, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 15, title: 'How to Use a Secured Credit Card to Build Credit', description: 'Step-by-step guide to using a secured card to build or rebuild your credit score.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_05', order: 16, title: 'The FICO Score Formula Explained', description: 'Break down the five components of your FICO score and how each one is weighted.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 17, title: 'What Lenders Actually Look For', description: 'Understand how lenders evaluate creditworthiness beyond just the score.', estimated_minutes: 45, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 18, title: 'How to Get Approved for an Apartment with Bad Credit', description: 'Strategies and tools for renting housing when your credit is damaged.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 19, title: 'How to Get Approved for a Car Loan with Bad Credit', description: 'Navigate auto lending when your credit is poor, including avoiding dealer traps.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 20, title: 'First-Time Homebuyer Basics for People Rebuilding Credit', description: 'What you need to know about buying a home when you are still rebuilding your financial life.', estimated_minutes: 60, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 21, title: 'Investment Basics for Beginners', description: 'Introduction to stocks, bonds, mutual funds, and how to start investing with very little money.', estimated_minutes: 55, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 22, title: 'Retirement Accounts Explained Simply', description: 'Understand 401(k), IRA, and Roth IRA accounts and why starting early matters.', estimated_minutes: 50, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 23, title: 'How to Read a Pay Stub', description: 'Understand every deduction and line item on your paycheck so nothing is a surprise.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_05', order: 24, title: 'Understanding Insurance Basics', description: 'Health, auto, renters, and life insurance: what you need, why it matters, and how to afford it.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_05', order: 25, title: 'How to Create a Debt Payoff Plan', description: 'Build a personalized debt payoff plan using avalanche and snowball methods.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },

  // Track 6 - Digital Literacy
  { track_id: 'track_06', order: 1, title: 'Basic Smartphone Skills', description: 'Essential smartphone skills including calls, texts, apps, settings, and storage management.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 2, title: 'Basic Computer Skills', description: 'Learn to use a computer including keyboard, mouse, files, and basic software.', estimated_minutes: 60, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 3, title: 'Internet Safety', description: 'Browse the internet safely and protect your personal information online.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 4, title: 'Email Setup and Email Etiquette', description: 'Set up a professional email account and learn to communicate effectively via email.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 5, title: 'Using Google Docs and Forms', description: 'Create, edit, and share documents using Google Docs for work and personal use.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_06', order: 6, title: 'Uploading Documents', description: 'Learn how to scan, upload, and share documents digitally for applications and appointments.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 7, title: 'Scanning IDs and Paperwork with a Phone', description: 'Use your phone camera to scan and digitize important documents for safe storage and sharing.', estimated_minutes: 25, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_06', order: 8, title: 'Online Job Search', description: 'Use online tools and resources to search for jobs effectively from your phone or computer.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 9, title: 'Using Job Boards', description: 'Navigate Indeed, LinkedIn, and other job boards to find and apply for jobs.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 10, title: 'Virtual Interview Skills', description: 'Prepare for and ace video job interviews from your phone or computer.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 11, title: 'Telehealth and Online Appointments', description: 'Use telehealth apps to access healthcare, therapy, and medical appointments remotely.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_06', order: 12, title: 'How to Apply for Benefits Online', description: 'Navigate government websites to apply for SNAP, Medicaid, housing assistance, and more.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_06', order: 13, title: 'Digital File Organization', description: 'Organize your digital files and documents so you can always find what you need.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_06', order: 14, title: 'Passwords, Privacy, and Security', description: 'Create strong passwords, enable two-factor authentication, and protect your accounts.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 15, title: 'Video Conferencing Basics', description: 'Use Zoom, Google Meet, and other video platforms for work, appointments, and meetings.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_06', order: 16, title: 'Online Banking Basics', description: 'Manage your bank account online and through a mobile app safely and confidently.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 17, title: 'Avoiding Online Scams', description: 'Identify and avoid the most common online scams targeting vulnerable populations.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_06', order: 18, title: 'AI Basics for Everyday Life', description: 'Understand what AI is and how tools like ChatGPT can help you with daily tasks.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_06', order: 19, title: 'AI for Job Search and Resume Help', description: 'Use AI tools to improve your resume, write cover letters, and prepare for interviews.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_06', order: 20, title: 'Digital Literacy for Independent Living', description: 'Apply your digital skills to manage housing, bills, healthcare, and government services.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },

  // Track 7 - Recovery Wellness
  { track_id: 'track_07', order: 1, title: 'Recovery Foundations', description: 'Understand the science of addiction, the recovery process, and what true recovery looks like.', estimated_minutes: 50, difficulty: 'beginner', target_populations: ['recovery','reentry'], completion_required: true, prerequisites: [] },
  { track_id: 'track_07', order: 2, title: 'Relapse Prevention', description: 'Build your personal relapse prevention plan with specific strategies and warning signs.', estimated_minutes: 60, difficulty: 'intermediate', target_populations: ['recovery'], completion_required: true, prerequisites: [] },
  { track_id: 'track_07', order: 3, title: 'Triggers and Coping Skills', description: 'Identify your personal triggers and build a toolkit of healthy coping strategies.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['recovery'], completion_required: true, prerequisites: [] },
  { track_id: 'track_07', order: 4, title: 'Emotional Regulation', description: 'Develop skills to identify, understand, and manage your emotions in healthy ways.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 5, title: 'Stress Management', description: 'Evidence-based stress management techniques you can use every day.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 6, title: 'Healthy Routines', description: 'Build a daily routine that supports recovery, employment, and overall wellness.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_07', order: 7, title: 'Sleep, Nutrition, and Wellness', description: 'How sleep, food, and physical activity directly impact your recovery and mental health.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 8, title: 'Building Sober Support Networks', description: 'Build a support network that reinforces your recovery and helps you through hard times.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['recovery'], completion_required: true, prerequisites: [] },
  { track_id: 'track_07', order: 9, title: 'Healthy Relationships', description: 'Identify healthy vs unhealthy relationship patterns and build connections that support your growth.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 10, title: 'Setting Boundaries', description: 'Learn how to set and maintain healthy boundaries in relationships, work, and recovery.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 11, title: 'Anger Management', description: 'Understand anger triggers and develop constructive responses to anger and frustration.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 12, title: 'Trauma Awareness', description: 'Understand trauma, its effects on behavior, and how trauma-informed care can help.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 13, title: 'Grief and Loss', description: 'Navigate the grief process in healthy ways, including grief related to incarceration and recovery.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 14, title: 'How to Ask for Help Early', description: 'Overcome barriers to seeking help and learn how to reach out before reaching a crisis point.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_07', order: 15, title: 'Peer Support and Mentoring', description: 'Connect with peer support resources and understand how mentoring relationships work.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_07', order: 16, title: 'Self-Advocacy in Recovery', description: 'Learn how to advocate for yourself in healthcare, treatment, and support system settings.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['recovery'], completion_required: false, prerequisites: [] },

  // Track 8 - Life Management
  { track_id: 'track_08', order: 1, title: 'Daily Living Skills', description: 'Master the fundamental daily life skills that create stability and self-sufficiency.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_08', order: 2, title: 'Time Management', description: 'Organize your time effectively to meet obligations at work, home, and in your program.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_08', order: 3, title: 'Personal Hygiene and Self-Presentation', description: 'Develop personal hygiene habits and a professional appearance appropriate for work and daily life.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 4, title: 'Household Management', description: 'Manage a household including cleaning schedules, maintenance, safety, and organization.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 5, title: 'Meal Planning on a Budget', description: 'Plan nutritious meals for the week on a tight budget using smart shopping strategies.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 6, title: 'Grocery Shopping Skills', description: 'Navigate grocery stores efficiently and affordably using unit pricing, sales, and budgets.', estimated_minutes: 35, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 7, title: 'Transportation Basics', description: 'Navigate public transit, rideshare, and other transportation options to get where you need to go.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 8, title: 'Conflict Resolution', description: 'Resolve conflicts peacefully in household, work, and community settings.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 9, title: 'Communication Skills', description: 'Develop clear, assertive, and professional communication skills for all areas of life.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_08', order: 10, title: 'Problem Solving and Decision Making', description: 'Apply structured problem-solving approaches to challenges in your personal and professional life.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 11, title: 'Parenting and Family Reunification Basics', description: 'Navigate the process of reconnecting with and co-parenting children after incarceration or crisis.', estimated_minutes: 60, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 12, title: 'Community Etiquette', description: 'Understand community norms, neighbor relations, and civic participation.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 13, title: 'Legal Documents and Personal Records', description: 'Understand, organize, and protect your important legal documents and personal records.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_08', order: 14, title: 'How to Keep Important Paperwork', description: 'Create a personal document organization system so nothing important is ever lost.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_08', order: 15, title: 'Crisis Planning', description: 'Build a personal crisis plan so you know what to do when things go wrong.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_08', order: 16, title: 'Emergency Preparedness', description: 'Prepare for natural disasters, housing crises, medical emergencies, and other urgent situations.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },

  // Track 9 - Benefits IDs
  { track_id: 'track_09', order: 1, title: 'How to Get Your ID, Birth Certificate, and Social Security Card', description: 'Step-by-step process to obtain or replace government-issued identification documents.', estimated_minutes: 50, difficulty: 'beginner', target_populations: ['reentry','homeless'], completion_required: true, prerequisites: [] },
  { track_id: 'track_09', order: 2, title: 'Medicaid and Medicare Basics', description: 'Understand the difference between Medicaid and Medicare and how to enroll in both.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_09', order: 3, title: 'SNAP and TANF Basics', description: 'Learn how to apply for food assistance and temporary cash assistance programs.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_09', order: 4, title: 'SSI and SSDI Basics', description: 'Understand supplemental income and disability programs and how to apply.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_09', order: 5, title: 'Veteran Benefits Basics', description: 'Overview of VA benefits including healthcare, disability, housing, and education.', estimated_minutes: 50, difficulty: 'beginner', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_09', order: 6, title: 'Health Care Navigation', description: 'Navigate the healthcare system including finding providers, understanding insurance, and accessing care.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_09', order: 7, title: 'Court Fines, Fees, and Payment Plans', description: 'Understand your court-ordered financial obligations and how to set up manageable payment plans.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_09', order: 8, title: 'Child Support Navigation Basics', description: 'Understand child support orders, modification processes, and how to stay compliant.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_09', order: 9, title: 'Expungement and Record Relief Orientation', description: 'Introduction to record expungement, sealing, and other forms of criminal record relief.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_09', order: 10, title: 'How to Organize Personal Documents', description: 'Build a personal document system for all your government, financial, and legal paperwork.', estimated_minutes: 30, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_09', order: 11, title: 'How to Advocate for Yourself with Agencies', description: 'Skills and strategies for navigating government agencies, appealing denials, and getting results.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },

  // Track 10 - Veteran
  { track_id: 'track_10', order: 1, title: 'Understanding Your VA Benefits in Full', description: 'A comprehensive overview of all VA benefits available to veterans.', estimated_minutes: 60, difficulty: 'intermediate', target_populations: ['veteran'], completion_required: true, prerequisites: [] },
  { track_id: 'track_10', order: 2, title: 'Filing a VA Disability Claim', description: 'Step-by-step guide to filing a VA disability claim and getting the rating you deserve.', estimated_minutes: 60, difficulty: 'advanced', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_10', order: 3, title: 'VA Healthcare Navigation', description: 'Access and navigate VA healthcare facilities, telehealth, and mental health services.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_10', order: 4, title: 'Veteran Housing Programs and HUD-VASH', description: 'Access veteran-specific housing programs including HUD-VASH housing vouchers.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_10', order: 5, title: 'Transition from Military to Civilian Work Culture', description: 'Navigate the significant cultural shift from military to civilian workplace environments.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['veteran'], completion_required: true, prerequisites: [] },
  { track_id: 'track_10', order: 6, title: 'Military Skills to Civilian Resume Translation', description: 'Translate military occupational specialties and experiences into civilian job language.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['veteran'], completion_required: true, prerequisites: [] },
  { track_id: 'track_10', order: 7, title: 'Veteran Peer Support and Community', description: 'Connect with veteran peer support networks and community organizations.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_10', order: 8, title: 'PTSD and Mental Health Resources for Veterans', description: 'Access veteran-specific mental health resources, PTSD treatment, and crisis support.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_10', order: 9, title: 'Veteran Entrepreneurship Basics', description: 'Resources and programs available to help veterans start and grow businesses.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_10', order: 10, title: 'How to Access VA Education Benefits', description: 'Navigate the GI Bill and other VA education programs to continue your education.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_10', order: 11, title: 'SDVOSB and Veteran Business Certifications', description: 'Get certified as a Service-Disabled Veteran-Owned Small Business and access set-aside contracts.', estimated_minutes: 60, difficulty: 'advanced', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_10', order: 12, title: 'Federal Contracting Basics for Veterans', description: 'Introduction to government contracting and how veterans can compete for federal contracts.', estimated_minutes: 60, difficulty: 'advanced', target_populations: ['veteran'], completion_required: false, prerequisites: [] },

  // Track 11 - Legal Navigation
  { track_id: 'track_11', order: 1, title: 'Understanding Your Rights After Release', description: 'Know your constitutional and legal rights as a formerly incarcerated person.', estimated_minutes: 50, difficulty: 'beginner', target_populations: ['reentry'], completion_required: true, prerequisites: [] },
  { track_id: 'track_11', order: 2, title: 'How Probation and Parole Work', description: 'Detailed overview of probation and parole conditions, violations, and how to successfully complete supervision.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: true, prerequisites: [] },
  { track_id: 'track_11', order: 3, title: 'What a Background Check Shows and How to Explain It', description: 'Understand what appears on your background check and craft honest, strategic explanations.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: true, prerequisites: [] },
  { track_id: 'track_11', order: 4, title: 'Record Sealing and Expungement Basics', description: 'Understand eligibility and process for sealing or expunging criminal records in your state.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_11', order: 5, title: 'Child Custody and Family Court Basics', description: 'Navigate family court proceedings for custody, visitation, and family reunification.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_11', order: 6, title: 'How to Handle Court Fines and Fees', description: 'Strategies for managing court-ordered fines, fees, and payment obligations.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_11', order: 7, title: 'Navigating Civil Legal Aid', description: 'Find and access free civil legal assistance for housing, family, and consumer issues.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_11', order: 8, title: 'Voter Rights Restoration After Felony Conviction', description: 'Learn how to restore your voting rights after a felony conviction in your state.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_11', order: 9, title: 'How to Get a Driver License Reinstated', description: 'Steps to reinstate a suspended or revoked driver license in your state.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },
  { track_id: 'track_11', order: 10, title: 'Understanding Restraining Orders and Protective Orders', description: 'Understand the legal impact of restraining orders and how they affect your housing and employment.', estimated_minutes: 45, difficulty: 'intermediate', target_populations: ['reentry'], completion_required: false, prerequisites: [] },

  // Track 12 - Entrepreneurship
  { track_id: 'track_12', order: 1, title: 'Introduction to Self-Employment', description: 'Explore self-employment as a path to income and independence, including pros, cons, and realities.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: true, prerequisites: [] },
  { track_id: 'track_12', order: 2, title: 'Freelancing and Gig Work Basics', description: 'Start earning income through freelance platforms and gig economy apps.', estimated_minutes: 45, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_12', order: 3, title: 'Starting a Small Business with No Money', description: 'Launch a micro-business using free tools, sweat equity, and community resources.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_12', order: 4, title: 'Business Banking and Separating Finances', description: 'Open a business bank account and keep personal and business finances completely separate.', estimated_minutes: 40, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_12', order: 5, title: 'Taxes for Self-Employed People', description: 'Understand self-employment taxes, quarterly payments, and deductions.', estimated_minutes: 55, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_12', order: 6, title: 'How to Get a Business License', description: 'Navigate the process of registering your business and obtaining required licenses and permits.', estimated_minutes: 40, difficulty: 'beginner', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_12', order: 7, title: 'Building a Client Base from Scratch', description: 'Strategies for finding your first customers and building lasting client relationships.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_12', order: 8, title: 'Social Media for Small Business', description: 'Use social media platforms to market your business and attract customers at zero cost.', estimated_minutes: 50, difficulty: 'intermediate', target_populations: ['all'], completion_required: false, prerequisites: [] },
  { track_id: 'track_12', order: 9, title: 'How to Bid on Government Contracts as a Veteran', description: 'Navigate the federal procurement process and submit winning bids on government contracts.', estimated_minutes: 60, difficulty: 'advanced', target_populations: ['veteran'], completion_required: false, prerequisites: [] },
  { track_id: 'track_12', order: 10, title: 'Understanding Business Credit vs Personal Credit', description: 'Build business credit separately from personal credit to protect your finances and grow your business.', estimated_minutes: 50, difficulty: 'advanced', target_populations: ['all'], completion_required: false, prerequisites: [] },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    // Check if already seeded
    const existing = await base44.asServiceRole.entities.LearningTrack.list();
    if (existing.length > 0) {
      return Response.json({ message: 'Already seeded', tracks: existing.length });
    }

    // Create tracks
    const createdTracks = [];
    for (const track of TRACKS) {
      const created = await base44.asServiceRole.entities.LearningTrack.create(track);
      createdTracks.push(created);
    }

    // Get LearningClass schema to check if track_id field exists
    // Create classes with track_id reference
    const createdClasses = [];
    for (const cls of CLASSES) {
      const created = await base44.asServiceRole.entities.LearningClass.create({
        title: cls.title,
        description: cls.description,
        track_id: cls.track_id,
        order: cls.order,
        estimated_minutes: cls.estimated_minutes,
        difficulty: cls.difficulty,
        target_populations: cls.target_populations,
        completion_required: cls.completion_required,
        prerequisites: cls.prerequisites,
        category: 'life_skills',
        is_active: true,
      });
      createdClasses.push(created);
    }

    return Response.json({
      success: true,
      tracks_created: createdTracks.length,
      classes_created: createdClasses.length,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});